job_sites:
  crabi:
    url: https://boards.greenhouse.io/crabi
    queries:
      home_page: .opening
      vacancy: .app-title
      ubicacion: .location
      descripcion: p, class_ \= \'\', id\=\'content\'


  cabify:
    url:  https://boards.greenhouse.io/cabify
    queries:
      home_page: .opening
      vacancy: .app-title
      ubicacion: .location
      descripcion: ul, class_ \= \'\',id\=\'content\'



  mensajerosurbanos:
    url: https://boards.greenhouse.io/mensajerosurbanos
    queries:
      home_page: .opening
      vacancy: .app-title
      ubicacion: .location
      descripcion: ul, class_ \= \'\',id\=\'content\'


  nubank:
    url: https://boards.greenhouse.io/nubank
    queries:
      home_page: .opening
      vacancy: .app-title
      ubicacion: .location
      descripcion: ul, class_ \= \'\',id\=\'content\'